/* npm i -D playwright axe-core jsqr pngjs; node tarjeta/review/smoke.cjs
   Optional PLAYWRIGHT_MODULE, CHROMIUM_PATH, AXE_SCRIPT, JSQR_MODULE, PNG_MODULE. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const repo=path.resolve(__dirname,'../..'),out=process.env.QA_OUTPUT||__dirname;
const mime={'.html':'text/html','.js':'application/javascript','.css':'text/css','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png','.woff2':'font/woff2','.webmanifest':'application/manifest+json'};
const checks=[],errors=[],failed=[],external=[];let browser,server;
const record=(name,details)=>{checks.push({name,passed:true,...details});console.log('PASS',name);};
(async()=>{
 fs.mkdirSync(out,{recursive:true});server=http.createServer((req,res)=>{let pathname=decodeURIComponent(new URL(req.url,'http://local').pathname);if(pathname.endsWith('/'))pathname+='index.html';const file=path.resolve(repo,'.'+pathname);if(!file.startsWith(repo+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(error,data)=>{res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');if(error){res.writeHead(404);return res.end('Missing');}res.end(data);});});
 await new Promise(r=>server.listen(8765,'127.0.0.1',r));browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write'],acceptDownloads:true});
 await context.addInitScript(()=>{Object.defineProperty(navigator,'share',{value:undefined,configurable:true});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8765/')&&!r.url().startsWith('data:'))external.push(r.url());});
 const url='http://127.0.0.1:8765/tarjeta/?src=instagram&utm_source=ig&utm_medium=social&utm_campaign=card-v2&utm_content=bio&email=private@example.com';
 await page.goto(url);await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>window.dataLayer?.some(e=>e.event==='card_view'));
 await page.evaluate(()=>{document.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&/^(https:\/\/wa.me|tel:|mailto:)/.test(a.href))e.preventDefault();},true);});
 for(const key of ['vida','salud','medicare','retiro']){await page.locator('[data-service='+key+']').click();assert.equal(await page.locator('[data-service='+key+']').getAttribute('aria-pressed'),'true');const href=await page.locator('#serviceWa').getAttribute('href');assert.equal(new URL(href).pathname,'/17863548796');assert.ok(new URL(href).searchParams.get('text').includes(key==='vida'?'vida':key==='salud'?'salud':key==='medicare'?'Medicare':'retiro'));assert.ok(href.includes('utm_campaign'));}await page.locator('#serviceWa').click();await page.locator('#mainCta').click();await page.locator('a[href^="tel:"]').first().click();record('Selector de cuatro necesidades, WhatsApp contextual, teléfono y campaña');
 const axeFile=process.env.AXE_SCRIPT||require.resolve('axe-core/axe.min.js');
 async function axe(name){await page.addScriptTag({path:axeFile});const violations=await page.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));});assert.deepEqual(violations,[],name+': '+JSON.stringify(violations));}
 await page.locator('#abreCalc').click();for(const [id,value]of [['cD','15000'],['cI','60000'],['cH','180000'],['cN','2']])await page.locator('#'+id).fill(value);assert.equal(await page.locator('#cTotal').innerText(),'$890,000');await page.waitForTimeout(750);const calcMessage=new URL(await page.locator('#cWa').getAttribute('href')).searchParams.get('text');assert.ok(calcMessage.includes('$890,000'));assert.ok(!calcMessage.includes('60000')&&!calcMessage.includes('180,000'));await page.locator('#cWa').click();await axe('calculator');
 for(const bad of ['-1','2.5','11']){await page.locator('#cN').fill(bad);assert.equal(await page.locator('#cWa').getAttribute('aria-disabled'),'true');}
 for(const id of ['cD','cI','cH','cN'])await page.locator('#'+id).fill('0');assert.equal(await page.locator('#cTotal').innerText(),'$15,000');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'abreCalc');record('DIME: fórmula original, límites, supuestos, privacidad y foco');
 await page.locator('[data-lead]').first().click();await page.locator('#leadName').fill('Prueba Local');await page.locator('#leadPhone').fill('123');await page.locator('#leadForm button[type=submit]').click();assert.equal(await page.locator('#leadDraft').isVisible(),false);await page.locator('#leadPhone').fill('(786) 555-0199');await page.locator('#leadForm button[type=submit]').click();assert.equal(await page.locator('#leadDraft').isVisible(),false);await page.locator('#leadConsent').check();await page.locator('#leadForm button[type=submit]').click();assert.equal(await page.locator('#leadDraft').isVisible(),true);const mail=await page.locator('#sendEmail').getAttribute('href');assert.ok(mail.startsWith('mailto:wperezmedero@gmail.com?'));assert.ok(decodeURIComponent(mail).includes('Prueba Local'));await axe('form');await page.locator('#copyLead').click();assert.ok((await page.evaluate(()=>navigator.clipboard.readText())).includes('Prueba Local'));await page.keyboard.press('Escape');await page.locator('[data-service=salud]').click();await page.locator('[data-lead]').first().click();assert.equal(await page.locator('#leadDraft').isVisible(),false);assert.equal(await page.locator('#leadInterest').inputValue(),'salud');await page.keyboard.press('Escape');record('Formulario: validación, consentimiento, borrador veraz, correo, copia y cambio de interés');
 const downloadPromise=page.waitForEvent('download');await page.locator('#guardar').click();const contact=await downloadPromise;const contactPath=path.join(out,'test-contact.vcf');await contact.saveAs(contactPath);const vcard=fs.readFileSync(contactPath,'utf8');assert.ok(vcard.includes('TEL;TYPE=CELL,VOICE:+17863548796'));assert.ok(vcard.includes('ADR;TYPE=WORK:;;650 E 58th St;Hialeah;FL;33013;USA'));assert.ok(vcard.includes('ORG:William Pérez-Mederos\\, Agente de Seguros'));assert.ok(vcard.split('\r\n').every(line=>Buffer.byteLength(line)<=75));fs.unlinkSync(contactPath);record('vCard: descarga, datos originales, escape y UTF-8');
 await page.locator('#compartir').click();const share=await page.locator('#shareUrl').inputValue();assert.ok(share.startsWith('https://williamperezseguros.com/tarjeta/'));assert.ok(!share.includes('email'));assert.equal(new URL(share).searchParams.get('src'),'instagram');await page.locator('#copyShare').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),share);await page.keyboard.press('Escape');record('Compartir: fallback accesible y atribución sin parámetros ajenos');
 await page.locator('[data-qr]').first().click();await axe('qr');const qrUrl=await page.locator('#qrUrl').inputValue();const qrDownload=page.waitForEvent('download');await page.locator('#downloadQr').click();const qrPath=path.join(out,'test-qr.png');await(await qrDownload).saveAs(qrPath);const {PNG}=require(process.env.PNG_MODULE||'pngjs'),jsQR=require(process.env.JSQR_MODULE||'jsqr');const png=PNG.sync.read(fs.readFileSync(qrPath));const decoded=jsQR(new Uint8ClampedArray(png.data),png.width,png.height);assert.equal(decoded?.data,qrUrl);fs.unlinkSync(qrPath);await page.locator('#copyQr').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),qrUrl);await page.keyboard.press('Escape');record('QR: generación local, descarga y decodificación real', {url:qrUrl});
 const events=await page.evaluate(()=>window.dataLayer);for(const event of ['card_view','cta_main_click','service_selected','whatsapp_click','phone_click','save_contact','share_card','qr_open','calculator_start','calculator_complete','lead_form_open','lead_form_submit'])assert.ok(events.some(e=>e.event===event),event);assert.ok(!JSON.stringify(events).includes('Prueba Local'));assert.ok(!JSON.stringify(events).includes('5550199'));const stored=await page.evaluate(()=>JSON.stringify({...sessionStorage}));assert.ok(!stored.includes('Prueba Local')&&!stored.includes('5550199'));record('Los 12 eventos y almacenamiento sin nombre, teléfono o cifras DIME');
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>navigator.serviceWorker.controller);await page.evaluate(async()=>{const c=await caches.open('another-app');await c.put('/another-app',new Response('keep'));});await context.setOffline(true);await page.goto('http://127.0.0.1:8765/tarjeta/?src=offline');await page.waitForFunction(()=>window.dataLayer);await page.locator('#abreCalc').click();await page.locator('#cI').fill('60000');assert.equal(await page.locator('#cTotal').innerText(),'$615,000');await page.keyboard.press('Escape');await page.locator('[data-qr]').first().click();assert.equal(await page.locator('#qrCode canvas').count(),1);await page.keyboard.press('Escape');assert.ok(await page.evaluate(()=>caches.has('another-app')));await context.setOffline(false);record('PWA: navegación offline con campaña nueva, DIME, QR y caché ajena conservada');
 for(const [name,width,height] of [['desktop',1440,1000],['mobile',390,844],['small',320,740],['tablet',768,1024],['zoom200',720,500]]){
 await page.setViewportSize({width,height});await page.goto(url);await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+name);await axe(name);if(name==='mobile'||name==='desktop'){await page.screenshot({path:path.join(out,name+'-hero.jpg'),type:'jpeg',quality:88});await page.evaluate(async()=>{for(const im of document.images){im.loading='eager';try{await im.decode();}catch{}}});await page.screenshot({path:path.join(out,name+'.jpg'),type:'jpeg',quality:86,fullPage:true});}if(name==='mobile')assert.ok((await page.locator('#mainCta').boundingBox()).y<height);record('Viewport '+name+' '+width+'px: sin desbordes ni infracciones axe AA');
 }
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.btn').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');record('Movimiento reducido');
 const nojs=await browser.newContext({javaScriptEnabled:false});const plain=await nojs.newPage();await plain.goto(url);assert.ok(await plain.locator('a[href="tel:+17863548796"]').count());assert.ok(await plain.locator('a[href^="https://wa.me"]').count());assert.ok(await plain.locator('noscript').isVisible());await nojs.close();record('Contacto esencial sin JavaScript');
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);assert.deepEqual(external,[]);record('Consola limpia, recursos sin errores y sin solicitudes externas');
 fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),checks,errors,failed,external},null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.close();});
